#!/bin/sh

echo "Updating Git"
git fetch
git reset --hard origin/main
git pull

echo "Cleaning Docker"
docker container prune --force
docker rmi ebug
docker image prune

echo "Building Container"
docker build -t ebug .

echo "Completed!"