/**:                 # /** This will put all the parameters in every node
  ros__parameters:
    # setup (defaults)
    image_transport: raw  # image format: "raw" or "compressed"
    family:  36h11        # tag family name: 16h5, 25h9, 36h11, Standard41h12  
    size: 0.118           # default tag edge size in meter
    profile: false        # print profiling information to stdout

    # tuning of detection (defaults)
    max_hamming: 0        # maximum allowed hamming distance (corrected bits)
    detector:
      threads: 2          # number of threads
      decimate: 2.0       # decimate resolution for quad detection
      blur: 0.0           # sigma of Gaussian blur for quad detection
      refine: True        # snap to strong gradients
      sharpening: 0.25    # sharpening of decoded images
      debug: False        # write additional debugging images to current working directory

    #  # (optional) list of tags
    # # If defined, 'frames' and 'sizes' must have the same length as 'ids'.
    tag:
      ids:    [0,1,2,3]         # tag IDs for which to publish transform
      frames: ['0', '1', '2','3']   # frame names
 

    